spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
content:
  service:
    url: ${ALFRESCO_BASE_PATH:http://localhost:8080}
    security:
      basicAuth:
        username: ${ALFRESCO_USERNAME:admin}
        password: ${ALFRESCO_PASSWORD:admin}
application:
  search-batch-size: ${SEARCH_BATCH_SIZE:100}
  consumer-threads: ${CONSUMER_THREADS:2}
  consumer-timeout: ${CONSUMER_TIMEOUT:5000}